# Generated by Django 5.2 on 2025-05-02 17:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dimod_api", "0003_album_dicom_files"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="creator",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="album",
            name="filecount",
            field=models.IntegerField(default=0),
        ),
    ]
